### ISSUE TITLE
'NoneType' is not iterable when creating ModelFieldList with no data.

### ISSUE THREAD

**Issue by DavidTWco** [kvesteri/wtforms-alchemy#87]
Hi,

I'm working on using the ```ModelFieldList``` for one-to-many relationships [as described in the documentation here](https://wtforms-alchemy.readthedocs.org/en/latest/relationships.html#one-to-many-relations). They are being automatically generated by a custom Form Generation class similar to the default provided by wtforms-alchemy.

I recieve the following error when creating an instance of the generated form:

```
File "...\wtforms\fields\core.py", line 882, in process
    for obj_data in data:
TypeError: 'NoneType' object is not iterable
```

I've inspected the auto generated form class, and it looks as if the auto generated ```ModelFieldList``` has been created successfully. It's name matches up correctly with the property on the model that links to the foreign table as noted in the documentation.

I'm creating a new instance of the form as shown below (where ```self._form``` is the class). Regardless of whether ```request.form``` is passed in, the mentioned error occurs.

```python
self.form = self._form() if not hasattr(request, 'form') \
            else self._form(request.form)
```

I can't think of anything else that could be causing this error, all of the parameters to ```self.process``` are ```None``` and this successfully works with every other field, including a ```ModelForm``` field without the ```ModelFieldList``` (I am using a regular ```FormField``` in the ```ModelFieldList``` as per the documentation).

Is this a strange bug in the library or is there something I am doing wrong? The Expected Output is just a ```FieldList``` with a empty Form.

Thanks, David.

I've included the full traceback below.

**Full Traceback (paths shortened for brevity):**
```
Traceback (most recent call last):
  File "...\werkzeug\wsgi.py", line 650, in __call__
    return app(environ, start_response)
  File "...\flask\app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "...\app\middleware.py", line 61, in __call__
    return self.app(environ, start_response)
  File "...\flask\app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "...\flask\app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "...\flask\_compat.py", line 33, in reraise
    raise value
  File "...\flask\app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "...\flask\app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "...\flask\app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "...\flask\_compat.py", line 33, in reraise
    raise value
  File "...\flask\app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "...\flask_debugtoolbar\__init__.py", line 125, in dispatch_request
    return view_func(**req.view_args)
  File "...\flask\views.py", line 83, in view
    self = view.view_class(*class_args, **class_kwargs)
  File "...\app\frontend\views\individual.py", line 27, in __init__
    super(IndividualView, self).__init__(self, *args, **kwargs)
  File "...\app\frontend\views\base.py", line 35, in __init__
    else self._form(request.form)
  File "...\wtforms\form.py", line 212, in __call__
    return type.__call__(cls, *args, **kwargs)
  File "...\app\forms\ordering.py", line 40, in __init__
    super(FormOrderMixin, self).__init__(*args, **kwargs)
  File "...\wtforms_alchemy\__init__.py", line 289, in __init__
    super(ModelForm, self).__init__(*args, **kwargs)
  File "...\wtforms\form.py", line 278, in __init__
    self.process(formdata, obj, data=data, **kwargs)
  File "...\wtforms\form.py", line 132, in process
    field.process(formdata)
  File "...\wtforms\fields\core.py", line 882, in process
    for obj_data in data:
TypeError: 'NoneType' object is not iterable
```

**Comment by lisjump** [comment]
I'm running across this same error.  It happens when the ModelFieldList is blank because, for instance, a user has no posts.  If I populate the "many" side of the relationship with some fake data then everything works fine.  If I then delete the fake data, I receive this error.  I believe that when there is no data it returns a NoneType instead of an empty list.
